# Bash aliases

# I don't have a pip, but I have a ~/bin/python that runs python3
alias pip='python -m pip'
alias pydoc='python -m pydoc'

# wow
# such commit
# very push
# -- https://twitter.com/chris__martin/status/420992421673988096
alias wow='git status'
alias such=git
alias very=git

# no config file/environment for this
alias exa='exa --group-directories-first'

# hide squashfs mounts please, my ubuntu has so many
alias lsblk='lsblk -e 7'

# vim: ft=sh
