#!/bin/sh
# sourced by /bin/sh from /etc/X11/Xsession.d/55gnome-session_gnomerc
# beware of set -e!
set +e

# import environment ($PATH and other stuff), but first make sure the
# noninteractive shell check works in my .bashrc.   Yes, this is a hack.
old_PS1=$PS1
PS1=
. ~/.profile
PS1=$old_PS1

# turn the fricking keyboard bell off
xset -b

# call some scripts from ~/bin/
enable-wheel-emulation
enable-two-finger-scroll

set -e
